---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/properties/properties_by_owner/{owner}":
    parameters:
    - name: owner
      in: path
      description: owner
      required: true
      schema:
        type: string
    get:
      summary: properties_by_owner property
      responses:
        '200':
          description: successful
  "/properties/properties_by_owner":
    get:
      summary: properties_by_owner property
      responses:
        '200':
          description: successful
  "/properties/filter_by_bedrooms":
    get:
      summary: filter_by_bedrooms property
      responses:
        '200':
          description: successful
  "/properties/filter_by_bathrooms":
    get:
      summary: filter_by_bathrooms property
      responses:
        '200':
          description: successful
  "/properties/filter_by_address":
    get:
      summary: filter_by_address property
      responses:
        '200':
          description: successful
  "/properties/{id}/update_properties":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    patch:
      summary: update_properties property
      responses:
        '200':
          description: successful
  "/properties":
    get:
      summary: list properties
      responses:
        '200':
          description: successful
    post:
      summary: create property
      responses:
        '200':
          description: successful
  "/properties/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show property
      responses:
        '200':
          description: successful
    patch:
      summary: update property
      responses:
        '200':
          description: successful
    put:
      summary: update property
      responses:
        '200':
          description: successful
    delete:
      summary: delete property
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
