---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/properties":
    get:
      summary: list properties
      responses:
        '200':
          description: successful
    post:
      summary: create property
      responses:
        '200':
          description: successful
  "/api/v1/properties/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    put:
      summary: update property
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
