default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgres
  username: postgres
  password: postgres

test:
  <<: *default
  database: testdb
  username: postgres
  password: postgres


production:
  <<: *default
  # database: postgres
  # username: postgres
  # password: postgres
